nodeLinker: node-modules

# Enable verbose logging
logFilters:
  - code: YN0013
    level: info

# ESM support
supportedArchitectures:
  os: ["current"]
  cpu: ["current"]

# TypeScript support
enableGlobalCache: true